//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railway_Ticket_Book.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Mas
    {
        public int AID { get; set; }
        public string A_Mail { get; set; }
        public string A_pass { get; set; }
    }
}
