//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railway_Ticket_Book.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class customer
    {
        public int UID { get; set; }
        [Required(ErrorMessage ="First Name Required")]
        public string FName { get; set; }
        [Required(ErrorMessage ="Last Name Required")]
        public string LName { get; set; }
        [Required(ErrorMessage ="Email is Required")]
        [DataType(DataType.EmailAddress)]
        public string Main { get; set; }
        [Required(ErrorMessage ="Date of Birth is Required")]
        public Nullable<System.DateTime> DOB { get; set; }

        [Required,RegularExpression (@"^([0-9]{10})$",ErrorMessage ="Enter valid NID")]
        public Nullable<decimal> NID { get; set; }
        [Required]
        public string TYP { get; set; }
        [Required(ErrorMessage ="Password mandatory")]
        [DataType(DataType.Password)]
        [MinLength(6,ErrorMessage ="Min 6 characters"),MaxLength(8,ErrorMessage ="Max 8 characters")]
        public string Pword { get; set; }
    }
}
