//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railway_Ticket_Book.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PekkaEntities : DbContext
    {
        public PekkaEntities()
            : base("name=PekkaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<A_Mas> A_Mas { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<tranHistory> tranHistories { get; set; }
        public virtual DbSet<vehicle> vehicles { get; set; }
    }
}
