//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railway_Ticket_Book.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tranHistory
    {
        public int T_id { get; set; }
        public Nullable<decimal> Tran_no { get; set; }
        public string Momin { get; set; }
        public Nullable<int> Ac { get; set; }
        public Nullable<int> Non { get; set; }
        public Nullable<int> cab { get; set; }
        public Nullable<int> amount { get; set; }
        public string gmail { get; set; }
        public Nullable<System.DateTime> sent { get; set; }
        public string s_from { get; set; }
        public string Des { get; set; }
        public Nullable<System.DateTime> jouney { get; set; }
        public Nullable<System.TimeSpan> jourtime { get; set; }
    }
}
