//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railway_Ticket_Book.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class vehicle
    {
        
        public int RailId { get; set; }
        [Required(ErrorMessage ="Required")]
        public string RNm { get; set; }
        [Required(ErrorMessage ="Required")]
        public string s_start { get; set; }
        [Required(ErrorMessage = "Required")]
        public string s_des { get; set; }
        [Required(ErrorMessage = "Required")]
        public Nullable<System.DateTime> ar_date { get; set; }
        [Required(ErrorMessage = "Required")]
        public Nullable<int> A_seat { get; set; }
        [Required(ErrorMessage = "Required")]
        public Nullable<int> N_seat { get; set; }
        [Required(ErrorMessage = "Required")]
        public Nullable<int> C_seat { get; set; }
        [Required(ErrorMessage = "Required")]
        public Nullable<int> A_F { get; set; }
        [Required(ErrorMessage = "Required")]
        public Nullable<int> B_F { get; set; }
        [Required(ErrorMessage = "Required")]
        public Nullable<int> C_F { get; set; }
        [Required(ErrorMessage = "Required")]
        public Nullable<System.TimeSpan> R_tm { get; set; }
    }
}
